imports:
    - { resource: 'lti.yaml' }
    - { resource: 'users.yaml' }

parameters:
    lti.oidc.token.ttl: 500
    lti.oidc.state.ttl: 500
    lti.oidc.nonce.ttl: 500
    # OAuth2
    oauth2_public_key_path: '%env(resolve:OAUTH2_PUBLIC_KEY_PATH)%'
    oauth2_private_key_path: '%env(resolve:OAUTH2_PRIVATE_KEY_PATH)%'
    oauth2_private_key_pass_phrase: '%env(resolve:OAUTH2_PRIVATE_KEY_PASS_PHRASE)%'
    oauth2_encryption_key: '%env(resolve:OAUTH2_ENCRYPTION_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ### APPLICATION SERVICES ###
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    App\Lti\Core\Security\Key\KeyChainRepositoryInterface:
        factory:   ['@App\Lti\Builder\KeyChainRepositoryBuilder', 'build']
        arguments: ['%kernel.project_dir%/config/lti.yaml']

    App\Lti\Core\Platform\PlatformRepositoryInterface:
        factory:   ['@App\Lti\Builder\PlatformRepositoryBuilder', 'build']
        arguments: ['%kernel.project_dir%/config/lti.yaml']

    App\Lti\Core\Tool\ToolRepositoryInterface:
        factory:   ['@App\Lti\Builder\ToolRepositoryBuilder', 'build']
        arguments: ['%kernel.project_dir%/config/lti.yaml']

    App\Lti\Core\Deployment\DeploymentRepositoryInterface:
        factory:   ['@App\Lti\Builder\DeploymentRepositoryBuilder', 'build']
        arguments: ['%kernel.project_dir%/config/lti.yaml']

    App\Security\OAuth2\Factory\OAuth2CryptKeyFactory:
        lazy: true

    oauth2.public_key:
        lazy: true
        class: League\OAuth2\Server\CryptKey
        factory:   ['@App\Security\OAuth2\Factory\OAuth2CryptKeyFactory', 'create']
        arguments: ['%oauth2_public_key_path%']

    oauth2.private_key:
        lazy: true
        class: League\OAuth2\Server\CryptKey
        factory:   ['@App\Security\OAuth2\Factory\OAuth2CryptKeyFactory', 'create']
        arguments: ['%oauth2_private_key_path%', '%oauth2_private_key_pass_phrase%']

    App\Security\OAuth2\Factory\OAuth2AuthorizationServerFactory:
        arguments:
            $privateKey: '@oauth2.private_key'
            $encryptionKey: '%oauth2_encryption_key%'

    ### VENDORS SERVICES ###
    CoderCat\JWKToPEM\JWKConverter: ~

    Lcobucci\JWT\Parsing\Encoder: ~

    Lcobucci\JWT\Parser: ~

    Lcobucci\JWT\Signer:
        class: Lcobucci\JWT\Signer\Rsa\Sha256

    League\OAuth2\Server\AuthorizationServer:
        factory: ['@App\Security\OAuth2\Factory\OAuth2AuthorizationServerFactory', 'create']

    Symfony\Component\Yaml\Parser: ~

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
